/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Biel' at '8/3/16 3:57 PM' with Gradle 2.13
 *
 * @author Biel, @date 8/3/16 3:57 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
